"$schema" = 'https://starship.rs/config-schema.json'

format = """
$time$directory$git_branch$git_status$git_state$cmd_duration
$character"""

# Enable the blank line before the prompt
add_newline = true

[time]
disabled = false
format = "at [$time]($style) "
style = "bold grey"
use_12hr = true

[directory]
format = "in [$path]($style)[$read_only]($read_only_style) "
style = "bold cyan"
truncation_length = 3
truncate_to_repo = true
read_only = " [RO]"
read_only_style = "red"

[character]
success_symbol = "[❯](bold purple)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[❮](bold green)"

[git_branch]
symbol = ""
format = "on [$branch]($style) "
style = "bold grey"

[git_status]
format = "([$all_status$ahead_behind]($style) )"
style = "bold red"
conflicted = "="
ahead = ">"
behind = "<"
diverged = "<>"
untracked = "?"
stashed = "$"
modified = "!"
staged = "+"
renamed = "->"
deleted = "x"

[cmd_duration]
format = "for [$duration]($style) "
style = "bold yellow"
