[plugin]  
prepend_previewers = [  
  { url = "*.md", run = "rich-preview" }, # for markdown (.md) files
  { url = "*.rst", run = "rich-preview"}, # for restructured text (.rst) files
  { url = "*.ipynb", run = "rich-preview"}, # for jupyter notebooks (.ipynb)
  { url = "*.json", run = "rich-preview"}, # for json (.json) files
  { url = "*.csv", run = "duckdb" },  
  { url = "*.tsv", run = "duckdb" },  
  { url = "*.json", run = "duckdb" },  
  { url = "*.parquet", run = "duckdb" },  
  { url = "*.txt", run = "duckdb" },  
  { url = "*.xlsx", run = "duckdb" },  
  { url = "*.db", run = "duckdb" },
  { url = "*.duckdb", run = "duckdb" }
]


prepend_preloaders = [  
  { url = "*.csv", run = "duckdb", multi = false },  
  { url = "*.tsv", run = "duckdb", multi = false },  
  { url = "*.json", run = "duckdb", multi = false },  
  { url = "*.parquet", run = "duckdb", multi = false },
  { url = "*.txt", run = "duckdb", multi = false },  
  { url = "*.xlsx", run = "duckdb", multi = false }
]
